name: Unit Tests
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  browser-tests:
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_UNSAFE_PERM: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
          node-version: 16

      - name: Bootstrap
        run: npm ci

      - name: Build 🔧
        run: npm run compile

      - name: Unit tests
        run: npm run test:browser
      - name: Report Coverage
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          verbose: true